version: '3'
services:
  db:
    image: postgres
    container_name: postgres_db_container
    environment:
      POSTGRES_DB: cleanexample
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
  app:
    build:
      context: applications/app-service/
      dockerfile: Dockerfile
    container_name: clean_architecture_container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cleanexample
    ports:
      - "8080:8080"
    depends_on:
      - db